// MicroPDF - MuPDF API Compatible C Header
// Master header for fitz (core) functionality

#ifndef MUPDF_FITZ_H
#define MUPDF_FITZ_H

#ifdef __cplusplus
extern "C" {
#endif

#include "mupdf/fitz/archive.h"
#include "mupdf/fitz/band_writer.h"
#include "mupdf/fitz/barcode.h"
#include "mupdf/fitz/bidi.h"
#include "mupdf/fitz/bitmap.h"
#include "mupdf/fitz/buffer.h"
#include "mupdf/fitz/buffered_io.h"
#include "mupdf/fitz/cbz.h"
#include "mupdf/fitz/color.h"
#include "mupdf/fitz/colorspace.h"
#include "mupdf/fitz/compat.h"
#include "mupdf/fitz/compress.h"
#include "mupdf/fitz/context.h"
#include "mupdf/fitz/convenience.h"
#include "mupdf/fitz/cookie.h"
#include "mupdf/fitz/data_locality.h"
#include "mupdf/fitz/deskew.h"
#include "mupdf/fitz/device.h"
#include "mupdf/fitz/display_list.h"
#include "mupdf/fitz/draw_device.h"
#include "mupdf/fitz/epub.h"
#include "mupdf/fitz/filter.h"
#include "mupdf/fitz/font.h"
#include "mupdf/fitz/geometry.h"
#include "mupdf/fitz/glyph.h"
#include "mupdf/fitz/glyph_cache.h"
#include "mupdf/fitz/gpu.h"
#include "mupdf/fitz/hashmap_util.h"
#include "mupdf/fitz/heap.h"
#include "mupdf/fitz/hints.h"
#include "mupdf/fitz/hyphen.h"
#include "mupdf/fitz/image.h"
#include "mupdf/fitz/json.h"
#include "mupdf/fitz/link.h"
#include "mupdf/fitz/lockfree.h"
#include "mupdf/fitz/log.h"
#include "mupdf/fitz/memory_profiler.h"
#include "mupdf/fitz/mmap.h"
#include "mupdf/fitz/ocr.h"
#include "mupdf/fitz/office.h"
#include "mupdf/fitz/outline.h"
#include "mupdf/fitz/output.h"
#include "mupdf/fitz/path.h"
#include "mupdf/fitz/pdf_3d.h"
#include "mupdf/fitz/pdf_clean.h"
#include "mupdf/fitz/pdf_cmap.h"
#include "mupdf/fitz/pdf_conformance.h"
#include "mupdf/fitz/pdf_event.h"
#include "mupdf/fitz/pdf_font.h"
#include "mupdf/fitz/pdf_image_rewriter.h"
#include "mupdf/fitz/pdf_interpret.h"
#include "mupdf/fitz/pdf_javascript.h"
#include "mupdf/fitz/pdf_layer.h"
#include "mupdf/fitz/pdf_name_table.h"
#include "mupdf/fitz/pdf_page.h"
#include "mupdf/fitz/pdf_parse.h"
#include "mupdf/fitz/pdf_portfolio.h"
#include "mupdf/fitz/pdf_recolor.h"
#include "mupdf/fitz/pdf_redact.h"
#include "mupdf/fitz/pdf_resource.h"
#include "mupdf/fitz/pdf_signature.h"
#include "mupdf/fitz/pdf_xref.h"
#include "mupdf/fitz/pdf_zugferd.h"
#include "mupdf/fitz/pixmap.h"
#include "mupdf/fitz/pool.h"
#include "mupdf/fitz/separation.h"
#include "mupdf/fitz/shade.h"
#include "mupdf/fitz/simd_util.h"
#include "mupdf/fitz/stext.h"
#include "mupdf/fitz/store.h"
#include "mupdf/fitz/story.h"
#include "mupdf/fitz/stream.h"
#include "mupdf/fitz/string_util.h"
#include "mupdf/fitz/struct_layout.h"
#include "mupdf/fitz/svg.h"
#include "mupdf/fitz/table_detect.h"
#include "mupdf/fitz/text.h"
#include "mupdf/fitz/tile_render.h"
#include "mupdf/fitz/transition.h"
#include "mupdf/fitz/tree.h"
#include "mupdf/fitz/util.h"
#include "mupdf/fitz/write_pixmap.h"
#include "mupdf/fitz/writer.h"
#include "mupdf/fitz/xml.h"
#include "mupdf/fitz/xps.h"

#ifdef __cplusplus
}
#endif

#endif /* MUPDF_FITZ_H */
