use crate::engine::EngineState;
use crate::models::{
    AppSettings, DocumentId, OpenResult, RecentFile, RenderResult, SearchResultItem,
};
use crate::pdf_engine::RenderFilter;
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub enum Message {
    ResetZoom,
    OpenSettings,
    CloseSettings,
    SaveSettings(AppSettings),
    ToggleSidebar,
    ToggleFullscreen,
    ToggleKeyboardHelp,
    RotateClockwise,
    RotateCounterClockwise,
    AddBookmark,
    RemoveBookmark(usize),
    JumpToBookmark(usize),
    SetAnnotationMode(Option<crate::models::PendingAnnotationKind>),
    AnnotationDragStart { page: usize, x: f32, y: f32 },
    AnnotationDragUpdate { x: f32, y: f32 },
    AnnotationDragEnd,
    DeleteAnnotation(usize),
    Undo,
    Redo,
    SetFilter(RenderFilter),
    ToggleAutoCrop,
    DocumentOpenedWithPath((PathBuf, OpenResult)),
    OpenDocument,
    OpenFile(PathBuf),
    CloseTab(usize),
    SwitchTab(usize),
    NextPage,
    PrevPage,
    ZoomOut,
    ZoomIn,
    SetZoom(f32),
    JumpToPage(usize),
    PageInputChanged(String),
    PageInputSubmitted,
    ViewportChanged(f32, f32),
    RequestRender(usize),
    SidebarViewportChanged(f32),
    PageRendered(usize, f32, Result<RenderResult, String>),
    ThumbnailRendered(usize, f32, Result<RenderResult, String>),
    DocumentOpened(Result<OpenResult, String>),
    EngineInitialized(EngineState),
    Search(String),
    PerformSearch(String),
    SearchResult(crate::models::DocumentId, Result<Vec<SearchResultItem>, String>),
    NextSearchResult,
    PrevSearchResult,
    ClearSearch,
    ClearRecentFiles,
    ExtractText,
    TextExtracted(Result<String, String>),
    ExportImage,
    ExportImages,
    SaveAnnotations,
    AnnotationsSaved(Result<String, String>),
    AnnotationsLoaded(DocumentId, Vec<crate::models::Annotation>),
    ImageExported(Result<String, String>),
    OpenRecentFile(RecentFile),
    Error(String),
    ClearStatus,
    IcedEvent(iced::Event),
    ForceQuit,
    LinkClicked(crate::models::Hyperlink),
}
