use crate::engine::EngineState;
use crate::models::{
    AppSettings, DocumentId, OpenResult, PdfResult, RecentFile, RenderResult, SearchResultItem,
};
use crate::pdf_engine::RenderFilter;
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub enum Message {
    ResetZoom,
    OpenSettings,
    CloseSettings,
    SaveSettings(AppSettings),
    ToggleSidebar,
    ToggleFormsSidebar,
    ToggleFullscreen,
    ToggleKeyboardHelp,
    RotateClockwise,
    RotateCounterClockwise,
    AddBookmark,
    RemoveBookmark(usize),
    JumpToBookmark(usize),
    SetAnnotationMode(Option<crate::models::PendingAnnotationKind>),
    AnnotationDragStart { page: usize, x: f32, y: f32 },
    AnnotationDragUpdate { x: f32, y: f32 },
    AnnotationDragEnd,
    DeleteAnnotation(usize),
    Undo,
    Redo,
    SetFilter(RenderFilter),
    ToggleAutoCrop,
    DocumentOpenedWithPath((PathBuf, OpenResult)),
    OpenDocument,
    OpenFile(PathBuf),
    OpenRecentFile(RecentFile),
    ClearRecentFiles,
    CloseTab(usize),
    SwitchTab(usize),
    NextPage,
    PrevPage,
    ZoomOut,
    ZoomIn,
    SetZoom(f32),
    JumpToPage(usize),
    PageInputChanged(String),
    PageInputSubmitted,
    Search(String),
    PerformSearch(String),
    SearchResult(DocumentId, PdfResult<Vec<SearchResultItem>>),
    NextSearchResult,
    PrevSearchResult,
    ClearSearch,
    DocumentOpened(PdfResult<OpenResult>),
    PageRendered(usize, f32, PdfResult<RenderResult>),
    ThumbnailRendered(usize, f32, PdfResult<RenderResult>),
    RequestRender(usize),
    ViewportChanged(f32, f32),
    SidebarViewportChanged(f32),
    ExtractText,
    TextExtracted(PdfResult<String>),
    SaveAnnotations,
    AnnotationsSaved(PdfResult<String>),
    AnnotationsLoaded(DocumentId, Vec<crate::models::Annotation>),
    MergeDocuments(Vec<PathBuf>),
    DocumentsMerged(PdfResult<String>),
    LoadFormFields,
    FormFieldsLoaded(PdfResult<Vec<crate::models::FormField>>),
    FormFieldChanged(String, String),
    FillForm(Vec<crate::models::FormField>),
    FormFilled(PdfResult<String>),
    ExportImage,
    ImageExported(PdfResult<String>),
    ExportImages,
    Print,
    PrintDone(PdfResult<()>),
    AddWatermark(String),
    WatermarkDone(PdfResult<String>),
    EngineInitialized(EngineState),
    Error(String),
    ClearStatus,
    IcedEvent(iced::Event),
    LinkClicked(crate::models::Hyperlink),
    ForceQuit,
}
