use crate::engine::EngineState;
use crate::models::{AppSettings, DocumentId, RecentFile};
use crate::pdf_engine::{self, RenderFilter};
use std::path::PathBuf;
use std::sync::Arc;

#[derive(Debug, Clone)]
pub enum Message {
    ResetZoom,
    OpenSettings,
    CloseSettings,
    SaveSettings(AppSettings),
    ToggleSidebar,
    ToggleFullscreen,
    ToggleKeyboardHelp,
    RotateClockwise,
    RotateCounterClockwise,
    AddBookmark,
    RemoveBookmark(usize),
    JumpToBookmark(usize),
    AddHighlight,
    AddRectangle,
    DeleteAnnotation(usize),
    SetFilter(RenderFilter),
    ToggleAutoCrop,
    DocumentOpenedWithPath((PathBuf, (DocumentId, usize, Vec<f32>, f32, Vec<pdf_engine::Bookmark>))),
    OpenDocument,
    OpenFile(PathBuf),
    CloseTab(usize),
    SwitchTab(usize),
    NextPage,
    PrevPage,
    ZoomIn,
    ZoomOut,
    SetZoom(f32),
    JumpToPage(usize),
    ViewportChanged(f32, f32),
    RequestRender(usize),
    SidebarViewportChanged(f32),
    PageRendered(Result<(usize, u32, u32, Arc<Vec<u8>>), String>),
    DocumentOpened(Result<(DocumentId, usize, Vec<f32>, f32, Vec<pdf_engine::Bookmark>), String>),
    EngineInitialized(EngineState),
    Search(String),
    PerformSearch,
    SearchResult(Result<Vec<(usize, String, f32)>, String>),
    NextSearchResult,
    PrevSearchResult,
    ClearSearch,
    ExtractText,
    TextExtracted(Result<String, String>),
    ExportImage,
    ExportImages,
    SaveAnnotations,
    AnnotationsSaved(Result<String, String>),
    AnnotationsLoaded(DocumentId, Vec<crate::models::Annotation>),
    ImageExported(Result<String, String>),
    OpenRecentFile(RecentFile),
    Error(String),
    ClearStatus,
}
