name: Commit Lint

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Cocogitto
        uses: cocogitto/cocogitto-action@v3
      - name: Check Commit Messages
        run: cog check
